---
- name: Install nfs-common
  ansible.builtin.apt:
    name: nfs-common
    state: present

- name: Set idmapd domain
  ansible.builtin.lineinfile:
    path: /etc/idmapd.conf
    regexp: '^Domain\s*='
    insertafter: '^#\s*Domain\s*='
    firstmatch: 'yes'
    line: "Domain = {{ idmapd_domain }}"
  when: idmapd_domain
