---
- name: Add backend storage directory for /scratch
  ansible.builtin.file:
    path: "{{ scratch_backend_location }}"
    owner: root
    group: root
    mode: '1777'
    state: directory

- name: Add a /scratch symlink
  ansible.builtin.file:
    src: "{{ scratch_backend_location }}"
    dest: "{{ scratch_dir }}"
    owner: root
    group: root
    state: link
  when: not scratch_backend_location.startswith(scratch_dir)
