---
- name: reload apparmor
  ansible.builtin.service:
    name: apparmor.service
    state: reloaded

- name: udevadm reload
  ansible.builtin.command:
    cmd: "udevadm control --reload"
  listen: reload udevadm

- name: udevadm trigger
  ansible.builtin.command:
    cmd: "udevadm trigger"
  listen: reload udevadm
